version: 2
jobs:
    build_af:
      docker:
        - image: kubos/kubos-linux-dev:latest
      working_directory: ~/project/apollo-fusion
      steps:
        - checkout
        - run: ./build.sh | tee full_build.log
        # Note: store_artifacts will trigger a failure when `circleci build` is run locally
        - store_artifacts:
            path: full_build.log
        - store_artifacts:
            path: kubos-linux.tar.gz
        - store_artifacts:
            path: aux-sd.tar.gz
    apps_build:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: cd apps; cargo build
    apps_clippy:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: cd apps; cargo clippy
    apps_fmt:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: cd apps; cargo fmt -- --check
    apps_tar:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: cd tools; ./build-apps.sh
        - store_artifacts:
            path: tools/apps-$(date +%Y.%m.%d).tar.gz
    
workflows:
  version: 2
  build:
    jobs:
      - build_af:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: master
      - apps_build:
          filters:
            branches:
              ignore: master
      - apps_clippy:
          filters:
            branches:
              ignore: master
      - apps_fmt:
          filters:
            branches:
              ignore: master
      - apps_tar:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: master
        
