[app-service.addr]
ip = "0.0.0.0"
port = 8000

[clyde-3g-eps-service]
bus = "/dev/i2c-1"

[clyde-3g-eps-service.addr]
ip = "0.0.0.0"
port = 8001

[mai400-service.addr]
ip = "0.0.0.0"
port = 8002

[novatel-oem6-service]
bus = "/dev/ttyS4"

[novatel-oem6-service.addr]
ip = "0.0.0.0"
port = 8003

[pumpkin-mcu-service]

[pumpkin-mcu-service.modules]
[pumpkin-mcu-service.modules.sim]
address = 80
[pumpkin-mcu-service.modules.bim]
address = 82
[pumpkin-mcu-service.modules.pim]
address = 83
[pumpkin-mcu-service.modules.rhm]
address = 85
[pumpkin-mcu-service.modules.aim2]
address = 86
[pumpkin-mcu-service.modules.bm2]
address = 92

[pumpkin-mcu-service.addr]
ip = "0.0.0.0"
port = 8004

[telemetry-service]
database = "/home/system/kubos/telemetry.db"

[telemetry-service.addr]
ip = "0.0.0.0"
port = 8005

[file-transfer-service]
storage_dir = "/home/system/file-storage"

[file-transfer-service.addr]
ip = "0.0.0.0"
port = 8008

[monitor-service.addr]
ip = "0.0.0.0"
port = 8009

[shell-service.addr]
ip = "0.0.0.0"
port = 8010